### PR TITLE
fix Implicit and add _CoqProject, Makefile

### PR DESCRIPTION
**Pull request by npe9**

### CODE REVIEW

**Comment by ybertot** [comment]
I will discuss this with my colleagues here, but to my opinion the makefile, which is an automatically generated file, should not be added under git.  The README.md should simply be updated to include instructions on how to generate this makefile.

Thanks for all these maintenance operations.

**Comment by npe9** [comment]
@ybertot Please take another look. I've squashed the two commits, removed the Makefile and added instructions in the README.md.

**Comment by ybertot** [comment]
When compiling it on my machine, there is a warning that I don't understand.  I will investigate.  In the meanwhile the pull request seems completely legitimate to me.

**Comment by ybertot** [comment]
Thanks!

**Pull request merged**
